In [38]:
import numpy as np

mdiff = np.array([[0.3],
              [0.1],
              [0.3]])

mspec = np.array([[0.6],
              [0.6],
              [0.6]])

mamb = np.array([[0.1],
              [0.1],
              [0.1]])

mgls = 3

n = np.array([[1.1],
              [3.7],
              [3.9]])

l = np.array([[1.8],
              [1.6],
              [1.5]])

v = np.array([[4.7],
              [1.6],
              [3.2]])

s = np.array([[0.9],
              [0.9],
              [0.9]])


In [39]:
nhat = n/np.linalg.norm(n)
lhat = l/np.linalg.norm(l)
vhat = v/np.linalg.norm(v)

In [41]:
#r = np.array([[0.9],
#              [0.6],
#              [3.0]])
#rhat = r/np.linalg.norm(r)

# OR

rhat = 2*np.sum(lhat*nhat)*nhat - lhat

print(rhat)

[[-0.28032418]
 [ 0.62711238]
 [ 0.7267382 ]]


In [42]:
cdiff = (s*mdiff)*np.sum(nhat*lhat)

print(cdiff)

[[0.23845868]
 [0.07948623]
 [0.23845868]]


In [43]:
cspec = (s*mspec)*np.sum(vhat*rhat)**mgls

print(cspec)

[[0.02132306]
 [0.02132306]
 [0.02132306]]


In [44]:
camb = mamb * s

In [45]:
cfinal = cdiff + cspec + camb

print(cfinal)

[[0.34978175]
 [0.19080929]
 [0.34978175]]


In [ ]:
# Useful global scene variables
mamb = light["AmbientLight"]
s = light["LightColor"]
camb = light["AmbientLight"] * light["LightColor"]
l = light["DirectionToLight"]
lhat = l / np.linalg.norm(l)
r_0 = camera["LookFrom"]
pat = camera["LookAt"]
up = camera["Up"]
fov = camera["FieldOfView"]